### ISSUE TITLE
Error: Cannot find module 'chalk' when yarn install --production

### ISSUE THREAD

**Issue by garrychnca** [sramam/winston-cfg#1]
```
2018-05-07T13:29:01Z error An unexpected error occurred: "/<hide>/node_modules/winston-cfg: Command failed.
2018-05-07T13:29:01Z Exit code: 1
2018-05-07T13:29:01Z Command: sh
2018-05-07T13:29:01Z Arguments: -c node ./scripts/postinstall.js
2018-05-07T13:29:01Z Directory: /<hide>/node_modules/winston-cfg
2018-05-07T13:29:01Z Output:
2018-05-07T13:29:01Z module.js:549
2018-05-07T13:29:01Z throw err;
2018-05-07T13:29:01Z ^
2018-05-07T13:29:01Z 
2018-05-07T13:29:01Z Error: Cannot find module 'chalk'
2018-05-07T13:29:01Z at Function.Module._resolveFilename (module.js:547:15)
2018-05-07T13:29:01Z at Function.Module._load (module.js:474:25)
2018-05-07T13:29:01Z at Module.require (module.js:596:17)
2018-05-07T13:29:01Z at require (internal/module.js:11:18)
2018-05-07T13:29:01Z at Object.<anonymous> (/<hide>/node_modules/winston-cfg/scripts/tasks/repo-url.js:12:15)
2018-05-07T13:29:01Z at Module._compile (module.js:652:30)
2018-05-07T13:29:01Z at Object.Module._extensions..js (module.js:663:10)
2018-05-07T13:29:01Z at Module.load (module.js:565:32)
2018-05-07T13:29:01Z at tryModuleLoad (module.js:505:12)
2018-05-07T13:29:01Z at Function.Module._load (module.js:497:3)".
```

winston-cfg release used: 1.0.11

Root cause is:
* scripts/postinstall.js gets executed
* module chalk is required
* chalk is listed as devDependencies in **_your_** package.json
* devDependencies will not be installed when production flag is enabled during yarn install

Workaround:
* explicitly include chalk in the dependencies of _**my**_ package.json (...which is ugly since my app does not use it)

**Comment by sramam** [comment]
thanks for the report. Should be fixed by 7b54e6dd9bef6f6f9c08f18ed6354cd07e9c36de. It's been published to npm. Please reopen if you still see trouble.
